## Practice Midterm 1

In [3]:
import numpy as np

f = np.zeros(50)
f[0] = 0
f[1] = 1

for k in range(1, 49):
    f[k+1] = f[k] + f[k-1]

print(f)

[0.00000000e+00 1.00000000e+00 1.00000000e+00 2.00000000e+00
 3.00000000e+00 5.00000000e+00 8.00000000e+00 1.30000000e+01
 2.10000000e+01 3.40000000e+01 5.50000000e+01 8.90000000e+01
 1.44000000e+02 2.33000000e+02 3.77000000e+02 6.10000000e+02
 9.87000000e+02 1.59700000e+03 2.58400000e+03 4.18100000e+03
 6.76500000e+03 1.09460000e+04 1.77110000e+04 2.86570000e+04
 4.63680000e+04 7.50250000e+04 1.21393000e+05 1.96418000e+05
 3.17811000e+05 5.14229000e+05 8.32040000e+05 1.34626900e+06
 2.17830900e+06 3.52457800e+06 5.70288700e+06 9.22746500e+06
 1.49303520e+07 2.41578170e+07 3.90881690e+07 6.32459860e+07
 1.02334155e+08 1.65580141e+08 2.67914296e+08 4.33494437e+08
 7.01408733e+08 1.13490317e+09 1.83631190e+09 2.97121507e+09
 4.80752698e+09 7.77874205e+09]


In [2]:
for k in range(48):
    f[k+2] = f[k+1] + f[k]

print(f)

[0.00000000e+00 1.00000000e+00 1.00000000e+00 2.00000000e+00
 3.00000000e+00 5.00000000e+00 8.00000000e+00 1.30000000e+01
 2.10000000e+01 3.40000000e+01 5.50000000e+01 8.90000000e+01
 1.44000000e+02 2.33000000e+02 3.77000000e+02 6.10000000e+02
 9.87000000e+02 1.59700000e+03 2.58400000e+03 4.18100000e+03
 6.76500000e+03 1.09460000e+04 1.77110000e+04 2.86570000e+04
 4.63680000e+04 7.50250000e+04 1.21393000e+05 1.96418000e+05
 3.17811000e+05 5.14229000e+05 8.32040000e+05 1.34626900e+06
 2.17830900e+06 3.52457800e+06 5.70288700e+06 9.22746500e+06
 1.49303520e+07 2.41578170e+07 3.90881690e+07 6.32459860e+07
 1.02334155e+08 1.65580141e+08 2.67914296e+08 4.33494437e+08
 7.01408733e+08 1.13490317e+09 1.83631190e+09 2.97121507e+09
 4.80752698e+09 7.77874205e+09]


In [6]:
T = np.array([[1, 1, 1, 1, 1], [1, 2, 3, 4, 5], [1, 3, 6, 10, 15]])
T = T.reshape(5, 3)
print(T)

S = np.copy(T)
S[:, 1] = np.zeros(5)
print(S)

[[ 1  1  1]
 [ 1  1  1]
 [ 2  3  4]
 [ 5  1  3]
 [ 6 10 15]]
[[ 1  0  1]
 [ 1  0  1]
 [ 2  0  4]
 [ 5  0  3]
 [ 6  0 15]]


# Cheat sheet notes

1. matplotlib commands - color and style types
2. forward, backward, central difference scheme formulas and error orders
3.